### PR TITLE
universal newline encoding for project files, test for crlf file

### LINKED ISSUE #454: Regression: BSD 3-clause no longer recognized
### Describe the bug

The BSD 3-clause license is no longer being recognized.

### Steps to reproduce the behavior

Please see my repo here https://github.com/dyn4j/dyn4j and the LICENSE.md

### Expected behavior

The license is detected as BSD 3-clause

### Screenshots

N/A

### Additional context

This was working as of a week or two ago so it appears to be a regression.  I've tried to match the license content and format exactly (apart from name and years), but this did not seem to help.

### PR DESCRIPTION
**Pull request by mlinksva**
fixes #454

-----
[View rendered spec/fixtures/crlf-bsd/LICENSE.md](https://github.com/licensee/licensee/blob/universal_newline/spec/fixtures/crlf-bsd/LICENSE.md)

### CODE REVIEW

File: lib/licensee/project_files/project_file.rb [hunk 1]
```diff
@@ -40,6 +40,7 @@ def initialize(content, metadata = {})
         unless @content.valid_encoding?
           @content.encode!(ENCODING, **ENCODING_OPTIONS)
         end
+        @content.encode!(ENCODING, universal_newline: true)
```
Comment (benbalter) [inline lib/licensee/project_files/project_file.rb:43]: Would it make sense to add `universal_newline: true` to the encoding options hash above and always run line 41 instead? Alternatively, I could see this living in content normalizer, replacing `\r\n?` with `\n`

Comment (mlinksva) [reply lib/licensee/project_files/project_file.rb:43]: I was not able to get adding `universal_newline: true` to the encoding options and always running line 41. Tests involving non-UTF-8-encoded license obtain `ArgumentError: invalid byte sequence in UTF-8`. I'm not sure why, but it seems the operations conflict with each other somehow.

I didn't include int he content normalizer because I'd read (but did not test) that string.encode is much faster than a regex, and it seemed fair to consider a pre-normalization step, having to do with the file type rather than the content.

However if you'd prefer it live in the content normalizer for consistency purposes, happy to move it there.

**Review by benbalter — APPROVED** [review]
